version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: contackt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contackt
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: contackt-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/contackt?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: contackt-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
